Repository ksaini75/kcelectricalcontractorllc, pull requests merged in 2021-02, with the labels that each got.

#5 Set up and navbar
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.scss
  src/App.test.js
  src/components/NavigationBar/NavigationBar.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement

#11 adding the navigation bar
  package-lock.json
  src/App.scss
  src/Images/ken-logo.png
  src/components/NavigationBar/NavigationBar.js
Labels: ui update

#10 Landing page1.0
  package-lock.json
  src/App.scss
  src/Images/lightbulbs.jpg
  src/Images/lightbulbs_cut.png
  src/Images/lightbulbs_cut_dark.png
  src/components/LandingPage/LandingPage.js
  src/components/LandingPage/LandingPage.scss
  src/index.js
Labels: ui update

#13 hamburger color change
  src/App.scss
  src/components/LandingPage/LandingPage.scss
  src/components/NavigationBar/NavigationBar.js
Labels: bug

#16 Landing page1.0
  src/components/LandingPage/LandingPage.scss
Labels: bug

#20 button upgrade
  src/components/LandingPage/LandingPage.scss
Labels: bug

#21 About page
  package-lock.json
  package.json
  src/App.scss
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.scss
  src/index.js
Labels: enhancement, ui update

#24 adding services pages
  src/Images/broken-cable.png
  src/Images/multimeter.png
  src/Images/plug.png
  src/components/LandingPage/LandingPage.scss
  src/components/ServicePage/ServicePage.js
  src/components/ServicePage/ServicePage.scss
  src/index.js
Labels: enhancement, ui update

#28 service page scss bug
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.scss
  src/components/LandingPage/LandingPage.js
  src/components/ServicePage/ServicePage.js
  src/components/ServicePage/ServicePage.scss
  src/index.js
Labels: bug

#30 responsive layout
  src/App.scss
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.scss
  src/components/LandingPage/LandingPage.js
  src/components/LandingPage/LandingPage.scss
  src/index.js
Labels: bug, ui update
