Repository ksaini75/kcelectricalcontractorllc, pull requests merged in 2021-03, with the labels that each got.

#31 service page rework
  src/components/AboutPage/AboutPage.scss
  src/components/LandingPage/LandingPage.js
  src/components/NavigationBar/NavigationBar.js
  src/components/ServicePage/ServicePage.js
  src/components/ServicePage/ServicePage.scss
Labels: bug, ui update

#33 style change
  src/components/AboutPage/AboutPage.js
  src/components/LandingPage/LandingPage.js
  src/components/NavigationBar/NavigationBar.js
  src/components/ServicePage/ServicePage.js
Labels: documentation

#32 Footer section
  package-lock.json
  package.json
  src/components/AboutPage/AboutPage.scss
  src/components/FooterPage/Footer.js
  src/components/FooterPage/Footer.scss
  src/index.js
Labels: ui update

#39 Email js
  .gitignore
  package-lock.json
  package.json
  public/icon.png
  public/index.html
  src/components/ContactPage/ContactPage.js
  src/components/ContactPage/ContactPage.scss
  src/components/LandingPage/LandingPage.js
  src/components/NavigationBar/NavigationBar.js
  src/index.js
Labels: ui update

#40 margin bottom-2 submit btn
  package-lock.json
  package.json
  src/App.scss
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.scss
  src/components/ContactPage/ContactPage.js
  src/components/ContactPage/ContactPage.scss
  src/components/FooterPage/Footer.js
  src/components/ServicePage/ServicePage.js
  src/components/ServicePage/ServicePage.scss
  src/index.js
Labels: ui update
